name: coder_matthews_extensions
description: A collection of useful extensions used in most of my personal projects
repository: https://github.com/Maker2000/coder_matthews_extensions
version: 1.9.6
# homepage: https://www.example.com

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.3.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.16.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

dependencies:
  intl: ^0.19.0
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  http: ^1.2.1

flutter:
  plugin:
    platforms:
      android:
        package: org.codemaker.coder_matthews_extensions
        pluginClass: CoderMatthewsExtensionsPlugin
      ios:
        pluginClass: CoderMatthewsExtensionsPlugin
