name: coder_matthews_extensions
description: A collection of useful extensions used in most of my personal projects
repository: https://github.com/Maker2000/coder_matthews_extensions
version: 1.0.1
# homepage: https://www.example.com

environment:
  sdk: ">=2.18.4 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  intl: ^0.18.0
